<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Theme extends \App\Entity\Theme implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Theme' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Theme' . "\0" . 'imageFond', '' . "\0" . 'App\\Entity\\Theme' . "\0" . 'imageFile', '' . "\0" . 'App\\Entity\\Theme' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Theme' . "\0" . 'url_img', '' . "\0" . 'App\\Entity\\Theme' . "\0" . 'isParametred', '' . "\0" . 'App\\Entity\\Theme' . "\0" . 'wishlists', '' . "\0" . 'App\\Entity\\Theme' . "\0" . 'updated_at'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Theme' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Theme' . "\0" . 'imageFond', '' . "\0" . 'App\\Entity\\Theme' . "\0" . 'imageFile', '' . "\0" . 'App\\Entity\\Theme' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Theme' . "\0" . 'url_img', '' . "\0" . 'App\\Entity\\Theme' . "\0" . 'isParametred', '' . "\0" . 'App\\Entity\\Theme' . "\0" . 'wishlists', '' . "\0" . 'App\\Entity\\Theme' . "\0" . 'updated_at'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Theme $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageFond(?string $imageFond)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageFond', [$imageFond]);

        return parent::setImageFond($imageFond);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageFond(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageFond', []);

        return parent::getImageFond();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageFile(?\Symfony\Component\HttpFoundation\File\File $imageFile): \App\Entity\Theme
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageFile', [$imageFile]);

        return parent::setImageFile($imageFile);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageFile(): ?\Symfony\Component\HttpFoundation\File\File
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageFile', []);

        return parent::getImageFile();
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name): \App\Entity\Theme
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrlImg(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrlImg', []);

        return parent::getUrlImg();
    }

    /**
     * {@inheritDoc}
     */
    public function setUrlImg(?string $url_img): \App\Entity\Theme
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrlImg', [$url_img]);

        return parent::setUrlImg($url_img);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsParametred(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsParametred', []);

        return parent::getIsParametred();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsParametred(bool $isParametred): \App\Entity\Theme
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsParametred', [$isParametred]);

        return parent::setIsParametred($isParametred);
    }

    /**
     * {@inheritDoc}
     */
    public function getWishlists(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWishlists', []);

        return parent::getWishlists();
    }

    /**
     * {@inheritDoc}
     */
    public function addWishlist(\App\Entity\Wishlist $wishlist): \App\Entity\Theme
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addWishlist', [$wishlist]);

        return parent::addWishlist($wishlist);
    }

    /**
     * {@inheritDoc}
     */
    public function removeWishlist(\App\Entity\Wishlist $wishlist): \App\Entity\Theme
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeWishlist', [$wishlist]);

        return parent::removeWishlist($wishlist);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(\DateTimeInterface $updated_at): \App\Entity\Theme
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updated_at]);

        return parent::setUpdatedAt($updated_at);
    }

}
