<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Wishlist extends \App\Entity\Wishlist implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Wishlist' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Wishlist' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\Wishlist' . "\0" . 'destinataire', '' . "\0" . 'App\\Entity\\Wishlist' . "\0" . 'budget', '' . "\0" . 'App\\Entity\\Wishlist' . "\0" . 'isparametree', '' . "\0" . 'App\\Entity\\Wishlist' . "\0" . 'dateexpiration', '' . "\0" . 'App\\Entity\\Wishlist' . "\0" . 'dateCreation', '' . "\0" . 'App\\Entity\\Wishlist' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Wishlist' . "\0" . 'user', '' . "\0" . 'App\\Entity\\Wishlist' . "\0" . 'theme', '' . "\0" . 'App\\Entity\\Wishlist' . "\0" . 'updated_at', '' . "\0" . 'App\\Entity\\Wishlist' . "\0" . 'imageFond', '' . "\0" . 'App\\Entity\\Wishlist' . "\0" . 'imageFile', '' . "\0" . 'App\\Entity\\Wishlist' . "\0" . 'articles', '' . "\0" . 'App\\Entity\\Wishlist' . "\0" . 'wishlist'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Wishlist' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Wishlist' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\Wishlist' . "\0" . 'destinataire', '' . "\0" . 'App\\Entity\\Wishlist' . "\0" . 'budget', '' . "\0" . 'App\\Entity\\Wishlist' . "\0" . 'isparametree', '' . "\0" . 'App\\Entity\\Wishlist' . "\0" . 'dateexpiration', '' . "\0" . 'App\\Entity\\Wishlist' . "\0" . 'dateCreation', '' . "\0" . 'App\\Entity\\Wishlist' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Wishlist' . "\0" . 'user', '' . "\0" . 'App\\Entity\\Wishlist' . "\0" . 'theme', '' . "\0" . 'App\\Entity\\Wishlist' . "\0" . 'updated_at', '' . "\0" . 'App\\Entity\\Wishlist' . "\0" . 'imageFond', '' . "\0" . 'App\\Entity\\Wishlist' . "\0" . 'imageFile', '' . "\0" . 'App\\Entity\\Wishlist' . "\0" . 'articles', '' . "\0" . 'App\\Entity\\Wishlist' . "\0" . 'wishlist'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Wishlist $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom(string $nom): \App\Entity\Wishlist
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getDestinataire(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDestinataire', []);

        return parent::getDestinataire();
    }

    /**
     * {@inheritDoc}
     */
    public function setDestinataire(string $destinataire): \App\Entity\Wishlist
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDestinataire', [$destinataire]);

        return parent::setDestinataire($destinataire);
    }

    /**
     * {@inheritDoc}
     */
    public function getBudget(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBudget', []);

        return parent::getBudget();
    }

    /**
     * {@inheritDoc}
     */
    public function setBudget(int $budget): \App\Entity\Wishlist
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBudget', [$budget]);

        return parent::setBudget($budget);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsparametree(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsparametree', []);

        return parent::getIsparametree();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsparametree(bool $isparametree): \App\Entity\Wishlist
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsparametree', [$isparametree]);

        return parent::setIsparametree($isparametree);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateexpiration(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateexpiration', []);

        return parent::getDateexpiration();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateexpiration(\DateTimeInterface $dateexpiration): \App\Entity\Wishlist
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateexpiration', [$dateexpiration]);

        return parent::setDateexpiration($dateexpiration);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreation(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreation', []);

        return parent::getDateCreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreation(\DateTimeInterface $dateCreation): \App\Entity\Wishlist
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreation', [$dateCreation]);

        return parent::setDateCreation($dateCreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(string $description): \App\Entity\Wishlist
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(?\App\Entity\User $user): \App\Entity\Wishlist
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getTheme(): ?\App\Entity\Theme
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTheme', []);

        return parent::getTheme();
    }

    /**
     * {@inheritDoc}
     */
    public function setTheme(?\App\Entity\Theme $theme): \App\Entity\Wishlist
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTheme', [$theme]);

        return parent::setTheme($theme);
    }

    /**
     * {@inheritDoc}
     */
    public function getArticles(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArticles', []);

        return parent::getArticles();
    }

    /**
     * {@inheritDoc}
     */
    public function addArticle(\App\Entity\Article $article): \App\Entity\Wishlist
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addArticle', [$article]);

        return parent::addArticle($article);
    }

    /**
     * {@inheritDoc}
     */
    public function removeArticle(\App\Entity\Article $article): \App\Entity\Wishlist
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeArticle', [$article]);

        return parent::removeArticle($article);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getWishlist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWishlist', []);

        return parent::getWishlist();
    }

    /**
     * {@inheritDoc}
     */
    public function setWishlist($wishlist)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWishlist', [$wishlist]);

        return parent::setWishlist($wishlist);
    }

    /**
     * {@inheritDoc}
     */
    public function setImageFond(?string $imageFond)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageFond', [$imageFond]);

        return parent::setImageFond($imageFond);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageFond(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageFond', []);

        return parent::getImageFond();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageFile(?\Symfony\Component\HttpFoundation\File\File $imageFile): \App\Entity\Wishlist
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageFile', [$imageFile]);

        return parent::setImageFile($imageFile);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageFile(): ?\Symfony\Component\HttpFoundation\File\File
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageFile', []);

        return parent::getImageFile();
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(\DateTimeInterface $updated_at): \App\Entity\Wishlist
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updated_at]);

        return parent::setUpdatedAt($updated_at);
    }

}
