<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ2NLFSJ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ2NLFSJ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJ2NLFSJ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJ2NLFSJ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerJ2NLFSJ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'J2NLFSJ',
    'container.build_id' => '2db6b780',
    'container.build_time' => 1601897154,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ2NLFSJ');
