<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBIOUfhy\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBIOUfhy/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBIOUfhy.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBIOUfhy\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerBIOUfhy\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'BIOUfhy',
    'container.build_id' => '0678b737',
    'container.build_time' => 1588092774,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBIOUfhy');
