<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUfQZpEa\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUfQZpEa/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUfQZpEa.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUfQZpEa\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerUfQZpEa\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'UfQZpEa',
    'container.build_id' => '506d3330',
    'container.build_time' => 1601897326,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUfQZpEa');
